"""A stored analysis for the demo button, so the product can be seen in one click.

A judge should not have to wait for a clone, a parse and a set of model calls
before they can tell whether this thing works. This module serves an analysis
that was produced by the real pipeline and committed alongside the code.

Where it comes from, honestly:

* ``server/demo/*.snapshot.json`` holds analyses generated by
  ``python -m app.scripts.build_demo`` against real public repositories. Each file
  carries the repository it describes and the commit it was taken at.
* The clone those analyses refer to is not committed. Anything that needs the
  clone - reading a file, the chat tools, the fix advisor - therefore reports
  that it is unavailable rather than pretending. Everything computed from the
  analysis itself - graph, hotspots, findings, dependency research, architecture
  summary - is fully present.
* If no stored analysis matches, and a live run is allowed, the caller is told
  to run the real analysis instead. The demo never fabricates a result.
"""

from __future__ import annotations

import json
import os
from typing import Any

DEMO_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "demo"))
CATALOGUE_PATH = os.path.join(DEMO_DIR, "catalogue.json")

# Fields a stored snapshot carries that must not travel: where it was cloned to.
_PATH_FIELDS = ("repo_path",)


class DemoNotAvailable(RuntimeError):
    """No stored analysis matches what was asked for."""


def catalogue() -> list[dict[str, Any]]:
    """The demo analyses available in this checkout, cheapest-looking first."""
    entries = _read_json(CATALOGUE_PATH)
    if not isinstance(entries, list):
        return []
    return [entry for entry in entries if isinstance(entry, dict) and entry.get("snapshot")]


def get_demo(slug: str) -> dict[str, Any]:
    """Load one stored analysis by its catalogue slug.

    The clone path is cleared on the way out: the directory it names exists on
    the machine that generated the file and nowhere else, and handing it on would
    produce a confusing 500 the first time someone asked for a file.
    """
    if not slug or "/" in slug or "\\" in slug or slug.startswith("."):
        raise DemoNotAvailable("That demo analysis does not exist.")

    entry = next((item for item in catalogue() if item.get("slug") == slug), None)
    if entry is None:
        raise DemoNotAvailable("That demo analysis does not exist.")

    snapshot = _read_json(os.path.join(DEMO_DIR, str(entry.get("snapshot", ""))))
    if not snapshot:
        raise DemoNotAvailable("The stored demo analysis could not be read.")

    snapshot = dict(snapshot)
    snapshot["repo_path"] = ""
    snapshot["demo"] = {
        "slug": slug,
        "label": entry.get("label", slug),
        "repo_url": entry.get("repo_url", snapshot.get("repo_url", "")),
        "generated_at": entry.get("generated_at", snapshot.get("analyzed_at", "")),
        "head_sha": entry.get("head_sha", snapshot.get("head_sha", "")),
        "live_required_for": ["file contents", "chat tools", "fix advisor"],
    }
    return snapshot


def _read_json(path: str) -> Any:
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError):
        return None